/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89. By considering the terms 
in the Fibonacci sequence whose values do not exceed 4,000,000, write a program that finds and prints 
the sum of the even-valued terms, followed by a new line.
You are allowed to use the standard library*/

#include <stdio.h>

int main(void)
{
    int i;
    int a, b, next, sum;

    i = 0;
    a = 1;
    b = 0;
    sum = 0;
    next = 0;
    while(next < 4000000)
    {
        next = a + b;
        b = a;
        a = next;
        if (next % 2 == 0)
        {
            sum += next;
        }
        i++;   
    }
    printf("%d\n", sum);
    return (0);
}
