#!/bin/bash
# check if CFILE is set
if [ -z "$CFILE" ]; then
	echo "Error: CFILE env variable not set."
	exit 1
fi
# space after and befor [] is !
# If the variable CFILE is empty (-z), then run the commands between then and fi

# if <condition_command>
# then
    # Commands to run if condition is true
# fi

output_filename="${CFILE%.c}.o"

gcc -c "$CFILE" -o "$output_filename"
